### ISSUE TITLE
Legend Colors

### ISSUE THREAD

**Issue by josihoppe** [sedos-project/django_energysystem_viewer#5]
What colors should be used? Right now I have found an implementation that looks like this:

![grafik](https://github.com/sedos-project/django_energysystem_viewer/assets/116898820/80541512-ae39-4e0e-8a25-8b6885babbb5)

**Comment by henhuy** [comment]
@bereba could you have a look if those colors are okay?
Or is it important that your original colors are used?

**Comment by bereba** [comment]
Sorry for the late reply. This is fine for now. Maybe I will do some adjustments after defining the colors for the result view to be consistent.

**Comment by bereba** [comment]
Legend has now been implemented with plotly.
