### ISSUE TITLE
energysystemviewer selection

### ISSUE THREAD

**Issue by josihoppe** [sedos-project/django_energysystem_viewer#6]
add a way to select input data for network and abbriviation with navigation to these pages

- [x] either add dropdown to index page (http://127.0.0.1:8000) or create new page
- [x] add BackEnd Logic for forms to transfer the chosen structure/collection
- [ ] add missing energysystem links for navigation (in sedos)
- [ ] maybe add breadcurmbs?
- [x] add some kind of banner / navbar-information that tells you which structure you chose and has option to change that
- [ ] selected files have to be "saved" for different usage in: 
    - [x] abbreviation
    - [x] aggregation
    - [x] network
    - [x] collection
    - [x] artifacts
    - [x] processes

**Comment by henhuy** [comment]
done
